# -*- coding: utf-8 -*-
"""Individual Project 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B3-PDNcueYe-uNET4tqGsjJcZbHGO6kU
"""

import pandas as pd

df = pd.read_csv("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.csv")

def row_to_kml(row):

    name = row['place']
    magnitude = row['mag']
    time = row['time']
    longitude = row['longitude']
    latitude = row['latitude']

    kml = f'<Placemark>\n\t<name>{name}</name>\n\t<description>\n\t\t&lt;h1&gt;{magnitude} Magnitude earthquake at {time}&lt;/h1&gt;\n\t</description>\n\t<Point>\n\t\t<coordinates>{longitude}, {latitude}</coordinates>\n\t</Point>\n</Placemark>\n'

    return kml

kml = '<?xml version="1.0" encoding="UTF-8"?>\n<kml xmlns="http://www.opengis.net/kml/2.2">\n<Document>\n'
for index, row in df.iterrows():
    kml += row_to_kml(row)
kml += '</Document>\n</kml>'

with open('earthquakes.kml', 'w') as file:
    file.write(kml)
    print(kml)